name: Build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: |
          docker build . -t jonasbe25/discord-mod-bot:latest
      - name: docker push
        run: |
          docker push jonasbe25/discord-mod-bot:latest
  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest


      - name: Download kubeconfig
        run: |
          mkdir $HOME/.kube
          echo '${{ secrets.KUBECONFIG }}' >> $HOME/.kube/config


      - name: Deploy to cluster
        run: |
          kubectl apply -f kubernetes/jonas-server-config-map.yaml
          kubectl apply -f kubernetes/jonas-server-deployment.yaml
          kubectl rollout restart deployment jonas-server-dc-bot